name: 'wiz-cli'
on: 
  push:
    branches:
      - 'master'
  workflow_dispatch:
  

jobs:
  wiz-cli-image-scan:
    name: 'Wiz-cli Image Scan'
    runs-on: ubuntu-latest
    env:
      SCAN_PATH: "ci-cd-intro/Dockerfile" # Set the relative path in the repo to build the image from
      TAG: "hello-world" # Set the tag to use for the image
      POLICY: "Perkinelmer vulnerabilities policy" # Set the desired Wiz-cli policy to use

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Check out repository
      uses: actions/checkout@v2

    # It's possible to skip this step if this job is sceduled after an image-build job.
    # If that's the case, also set "Run wiz-cli docker image scan" step accordingly
    - name: Build the Docker image
      run: cd $SCAN_PATH && docker build . --tag $TAG # Configure to fit the params you use to build your image

    - name: Download Wiz-cli
      run: curl -o wizcli https://wizcli.app.wiz.io/wizcli && chmod +x wizcli

    - name: Authenticate to Wiz
      run: ./wizcli auth --id "YARC9Pr6B26SFkONOniyAoREfLO3MzJB" --secret "rbJQ0QGYQD1Ts-pKaF-SFEefBOrzUySYKkSeBXyH5JmBjxOfQyd5X49gaDQkmNgh"
      env:
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

    - name: Run wiz-cli docker image scan
      run: ./wizcli docker scan --image $TAG --policy "$POLICY"
